language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5"

sudo: false

notifications:
  email:
    - services@wikimedia.org

before_install:
  - wget https://archive.apache.org/dist/cassandra/2.2.6/apache-cassandra-2.2.6-bin.tar.gz -P ../
  - tar -xzf ../apache-cassandra-2.2.6-bin.tar.gz -C ../
  - sh ../apache-cassandra-2.2.6/bin/cassandra > /dev/null

script: npm run-script coverage && (npm run-script coveralls || exit 0)
